# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  neovim-stable = {
    pname = "neovim-stable";
    version = "v0.12.5";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "neovim";
      rev = "v0.12.5";
      fetchSubmodules = false;
      sha256 = "sha256-dpu2kncpm+2k+XR7qOEi4KeEy9a1E6X7kjf3s4AbcSo=";
    };
  };
}
